### ISSUE TITLE
Countdown with tplink hs300 isn't working

### ISSUE THREAD

**Issue by rrauenza** [jneilliii/OctoPrint-TPLinkSmartplug#109]
I'm getting the spinning lightning bolt, can't seem to get logging to work, and not getting any power status.  tcpdump isn't helpful I guess because of the xor encryption.

I know this is a new feature and I'd like to help resolve.

I'm also a little worried that when I got it today I upgraded the firmware... and that introduced an incompatibility. [edit: Nope!]

I've added logging.yaml to ~/.octoprint
```
pi@octopi:~/.octoprint $ more logging.yaml 
loggers:
  octoprint.plugins.tplinksmartplug:
    level: DEBUG
```

CC @romainrobotics, @ridencww

I found how to configure logging in octopi itself and now have:

```
pi@octopi:~/.octoprint $ less logging.yaml 
loggers:
  octoprint.plugins.tplinksmartplug:
    level: DEBUG
  octoprint.plugins.tplinksmartplug.debug:
    level: DEBUG
```

Now I'm getting logs.
