### ISSUE TITLE
[Question]: Is it possible to power on the smart plug when Octoprint starts?

### ISSUE THREAD

**Issue by Alwinator** [jneilliii/OctoPrint-TPLinkSmartplug#204]
It would be very convenient. By the way thank you for your great plugin! Thank you in advance.

**Comment by jneilliii** [comment]
There is a way, although a little convoluted. Create a new file called startup.sh in `/home/pi/.octoprint/scripts/` and put this into it, replacing the API KEY (you can get that from your user settings) and plug's ip address.
```
#!/bin/bash
curl -s -H "Content-Type: application/json" -H "X-Api-Key: PUTYOUTAPIKEYHERE" -X POST -d '{"command":"turnOn", "ip":"PUTYOURPLUGSIPHERE"}' https://127.0.0.1/api/plugin/tplinksmartplug
```

after creating the file you need to run this command to make it executable.

```
chmod +x /home/pi/.octoprint/scripts/startup.sh
```

and then edit your config.yaml to include the startup event by adding this.

```
events:
    subscriptions:
    -   command: /home/pi/.octoprint/scripts/startup.sh
        event: Startup
        type: system
```
