### ISSUE TITLE
GCode processing not working with IP address

### ISSUE THREAD

**Issue by xkcd42** [jneilliii/OctoPrint-TPLinkSmartplug#27]
I think I have the gcode correct with the IP address.  Log validates it ok, but it errors out at shutdown command.   
End of Gcode:
M84                         ;steppers off
G90                         ;absolute positioning
G4 P10000
M81 192.168.0.187
;{profile_string}

Debug log (repeats)
[2017-11-16 16:54:02,837] DEBUG: Checking status of 192.168.0.187.
[2017-11-16 16:54:02,840] DEBUG: IP 192.168.0.187 is valid.
[2017-11-16 16:54:02,949] DEBUG: Sending command info to 192.168.0.187
[2017-11-16 16:54:02,954] DEBUG: « 'õ"system":{"get_sysinfo":{"err_code":0,"sw_ver":"1.1.1 Build 160725 Rel.163650","hw_ver":"1.0","type":"IOT.SMARTPLUGSWITCH","model":"HS100(US)","mac":"xxxxxxxxxx","deviceId":"8006987341FA98689E31EFE2772EBABC17DC609E","hwId":"5EACBE93FB9E32ECBE1F1C2ADE6DDE11","fwId":"59542398207847F07D67AB57530532B8","oemId":"37589AA1F5CACDC53E2914B7760127E5","alias":"MPSM","dev_name":"Wi-Fi Smart Plug","icon_hash":"","relay_state":1,"on_time":10270,"active_mode":"schedule","feature":"TIM","updating":0,"rssi":-65,"led_off":0,"latitude":0,"longitude":0}}}
[2017-11-16 17:15:34,145] DEBUG: Checking status of 192.168.0.187.
[2017-11-16 17:15:34,146] DEBUG: IP 192.168.0.187 is valid.
[2017-11-16 17:15:34,298] DEBUG: Sending command info to 192.168.0.187
[2017-11-16 17:15:34,304] DEBUG: « 'õ"system":{"get_sysinfo":{"err_code":0,"sw_ver":"1.1.1 Build 160725 Rel.163650","hw_ver":"1.0","type":"IOT.SMARTPLUGSWITCH","model":"HS100(US)","mac":"xxxxxxxxxxx","deviceId":"8006987341FA98689E31EFE2772EBABC17DC609E","hwId":"5EACBE93FB9E32ECBE1F1C2ADE6DDE11","fwId":"59542398207847F07D67AB57530532B8","oemId":"37589AA1F5CACDC53E2914B7760127E5","alias":"MPSM","dev_name":"Wi-Fi Smart Plug","icon_hash":"","relay_state":1,"on_time":11562,"active_mode":"schedule","feature":"TIM","updating":0,"rssi":-68,"led_off":0,"latitude":0,"longitude":0}}}

**Comment by jneilliii** [comment]
Which version of the plugin? Can you upload the entire debug log and verify if you have any errors in the console or octoprint.log as well? Also in config.yaml make sure the plugs setting is enabled for gcodeprocessing like below where gcodeEnabled is set to true. 

```
  tplinksmartplug:
    _config_version: 3
    arrSmartplugs:
    - autoConnect: false
      autoConnectDelay: '15'
      autoDisconnect: false
      autoDisconnectDelay: 0
      btnColor: '#00FF00'
      currentState: 'on'
      displayWarning: false
      gcodeEnabled: true
      gcodeOffDelay: 0
      gcodeOnDelay: 0
      ip: 192.168.0.187
      sysCmdOff: false
      sysCmdOffDelay: 0
      sysCmdOn: false
      sysCmdOnDelay: 0
      sysRunCmdOff: ''
      sysRunCmdOn: ''
      warnPrinting: false
```

From what it looks like it never gets to the point where it sends the off command.  There should be a line in the debug log like "Received M81 command, attempting power off."

I might actually in the near future change the logic here because I think there's too much communication back and forth between the javascript client side and the python processing side with how it's set-up now.  When the gcode string is detected it sends a message to the javascript side to lookup up the plug in the array by ip, initiate a timer to send the instruction back to the python side to actually do the work, and then another message back to the javascript side to update the icon display.  I think I figured out a better way to do the lookup on the python side and will do it that way with python timers instead and take a round trip of communication out of the equation.
